### ISSUE TITLE
:first-child, :last-child

### ISSUE THREAD

**Issue by isachivka** [samsonos/php_skeleton#1]
Нужно добавлять что-то одно для одинаковых элементов в одном родителе, :first-child или :last-child задавать в конфиге, по умолчанию :first-child, и возможностью переключения на :last-of-type, :first-of-type

**Comment by vitalyiegorov** [comment]
Приведи пару разных примеров для тестирования, обязательно что бы были классы

**Comment by isachivka** [comment]
Хотелось бы получать из:

```
<div class="items">
  <div class="item"></div>
  <div class="item"></div>
  <div class="item"></div>
  <div class="item"></div>
</div>

<ul>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
</ul>
```

вот это:

```
.items {
  .item {
    &:last-child {
    }
  }
}

ul {
  li {
    &:last-child {
    }
  }
}
```

:last-child опционально переключается в :first-child (обычно верстальщики чаще всего цепляют что-то или к первому или к последнему, в зависимости от стиля кодинга), по умолчанию делайте last
